In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("data/raw/Telco-Customer-Churn.csv")

FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/Telco-Customer-Churn.csv'

In [6]:
df = pd.read_csv("data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [8]:
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [11]:
df.describe(include = 'all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
customerID,7043,7043,7590-VHVEG,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN
gender,7043,2,Male,3555,NaN,NaN,NaN,NaN,NaN,NaN,NaN
SeniorCitizen,7043.0,NaN,NaN,NaN,0.162147,0.368612,0.0,0.0,0.0,0.0,1.0
Partner,7043,2,No,3641,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Dependents,7043,2,No,4933,NaN,NaN,NaN,NaN,NaN,NaN,NaN
tenure,7043.0,NaN,NaN,NaN,32.371149,24.559481,0.0,9.0,29.0,55.0,72.0
PhoneService,7043,2,Yes,6361,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MultipleLines,7043,3,No,3390,NaN,NaN,NaN,NaN,NaN,NaN,NaN
InternetService,7043,3,Fiber optic,3096,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineSecurity,7043,3,No,3498,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OnlineBackup,7043,3,No,3088,NaN,NaN,NaN,NaN,NaN,NaN,NaN
DeviceProtection,7043,3,No,3095,NaN,NaN,NaN,NaN,NaN,NaN,NaN
TechSupport,7043,3,No,3473,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingTV,7043,3,No,2810,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StreamingMovies,7043,3,No,2785,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Contract,7043,3,Month-to-month,3875,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaperlessBilling,7043,2,Yes,4171,NaN,NaN,NaN,NaN,NaN,NaN,NaN
PaymentMethod,7043,4,Electronic check,2365,NaN,NaN,NaN,NaN,NaN,NaN,NaN
MonthlyCharges,7043.0,NaN,NaN,NaN,64.761692,30.090047,18.25,35.5,70.35,89.85,118.75
TotalCharges,7043,6531,,11,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Churn,7043,2,No,5174,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [12]:
df.dtypes.value_counts()

object     18
int64       2
float64     1
Name: count, dtype: int64

In [17]:
from textwrap import shorten

In [1]:
import pandas as pd
from textwrap import shorten
df = pd.read_csv("data/raw/WA_Fn-UseC_-Telco-Customer-Churn.csv")
def guess_dtype(series: pd.Series) -> str:
    """Return tidy dtype label for the data dictionary."""
    if pd.api.types.is_bool_dtype(series):
        return "bool"
    if pd.api.types.is_integer_dtype(series):
        # 仅含 0/1 视作二元信号
        return "int (0/1)" if set(series.dropna().unique()) <= {0, 1} else "int"
    if pd.api.types.is_float_dtype(series):
        return "float"
    return "string"  # 默认

def sample_val(series: pd.Series) -> str:
    val = series.dropna().iloc[0] if series.dropna().size else ""
    return shorten(str(val), width=12, placeholder="…")

# 初步信息表
info_df = pd.DataFrame({
    "Field Name": df.columns,
    "Data Type": [guess_dtype(df[c]) for c in df.columns],
    "Missing Count": df.isna().sum(),
    "Example Value": [sample_val(df[c]) for c in df.columns]
})

# 识别所有二元或有限级别的字符串列，改标为 category
cat_candidates = [
    c for c in df.columns
    if df[c].dtype == "object" and df[c].nunique() <= 10   # 阈值可调
]
info_df.loc[info_df["Field Name"].isin(cat_candidates), "Data Type"] = "category"

# 保存草稿
info_df[["Field Name", "Data Type", "Example Value"]].to_markdown(
    "data_dictionary_draft.md", index=False
)
print("✅  data_dictionary_draft.md generated")

✅  data_dictionary_draft.md generated